package ca.mcscert.jpipe.visitor;

import ca.mcscert.jpipe.model.Justification;
import ca.mcscert.jpipe.model.JustificationModel;
import ca.mcscert.jpipe.model.Template;
import ca.mcscert.jpipe.model.Unit;
import ca.mcscert.jpipe.model.elements.AbstractSupport;
import ca.mcscert.jpipe.model.elements.Conclusion;
import ca.mcscert.jpipe.model.elements.Evidence;
import ca.mcscert.jpipe.model.elements.JustificationElement;
import ca.mcscert.jpipe.model.elements.Strategy;
import ca.mcscert.jpipe.model.elements.SubConclusion;
import ca.mcscert.jpipe.util.LabelEscaper;
import java.time.Instant;

/**
 * Serialises a single {@link JustificationModel} to a Python module: each
 * element becomes a decorated function named after the element's label
 * (snake_case via {@link LabelEscaper}). Two decorators are emitted per
 * function:
 *
 * <ul>
 * <li>{@code # @jpipe_link("<modelName:elementId>")} — commented out until the
 * jpipe_link decorator is available at runtime.</li>
 * <li>{@code @jpipe(produce=[], consume=[])} — placeholder decorators to be
 * filled in by the developer.</li>
 * </ul>
 *
 * <p>
 * Each function carries a docstring with the original element label so the full
 * text is always recoverable regardless of escaping.
 *
 * <p>
 * This visitor operates on one model at a time. Use {@code SelectModel} in the
 * compilation pipeline to extract the desired model from a {@link Unit} before
 * invoking this exporter.
 */
public class PythonExporter implements JustificationVisitor<Void> {

	private String currentModelName;
	private final StringBuilder builder = new StringBuilder();

	/**
	 * Serialise {@code model} to Python source text without a file header.
	 *
	 * @param model
	 *            the justification or template to serialise.
	 * @return Python source text.
	 */
	public String export(JustificationModel<?> model) {
		return export(model, null);
	}

	/**
	 * Serialise {@code model} to Python source text, optionally prefixed with a
	 * generated-file header comment.
	 *
	 * @param model
	 *            the justification or template to serialise.
	 * @param sourcePath
	 *            path of the originating {@code .jd} file, included in the
	 *            header comment; may be {@code null} to omit the header.
	 * @return Python source text.
	 */
	public String export(JustificationModel<?> model, String sourcePath) {
		builder.setLength(0);
		if (sourcePath != null) {
			appendHeader(sourcePath);
		}
		appendPreamble();
		model.accept(this);
		return builder.toString();
	}

	// -------------------------------------------------------------------------
	// Unit and model visit methods
	// -------------------------------------------------------------------------

	@Override
	public Void visit(Unit unit) {
		throw new UnsupportedOperationException(
				"PythonExporter operates on a single model"
						+ " — use SelectModel to extract one from a Unit");
	}

	@Override
	public Void visit(Justification justification) {
		exportModelBody(justification);
		return null;
	}

	@Override
	public Void visit(Template template) {
		exportModelBody(template);
		return null;
	}

	// -------------------------------------------------------------------------
	// Element visit methods
	// -------------------------------------------------------------------------

	@Override
	public Void visit(Conclusion conclusion) {
		appendMethod(conclusion);
		return null;
	}

	@Override
	public Void visit(SubConclusion subConclusion) {
		appendMethod(subConclusion);
		return null;
	}

	@Override
	public Void visit(Strategy strategy) {
		appendMethod(strategy);
		return null;
	}

	@Override
	public Void visit(Evidence evidence) {
		appendMethod(evidence);
		return null;
	}

	@Override
	public Void visit(AbstractSupport abstractSupport) {
		appendMethod(abstractSupport);
		return null;
	}

	// -------------------------------------------------------------------------
	// Private helpers
	// -------------------------------------------------------------------------

	private void appendHeader(String sourcePath) {
		builder.append("# Generated by jPipe\n");
		builder.append("# Source : ").append(sourcePath).append("\n");
		builder.append("# Date   : ").append(Instant.now()).append("\n");
		builder.append("\n");
	}

	private void appendPreamble() {
		builder.append("from typing import Any, Callable\n");
		builder.append("from jpipe_runner.framework.decorators")
				.append(".jpipe_decorator import jpipe\n");
		builder.append("# from jpipe_runner.framework.decorators")
				.append(".jpipe_decorator import jpipe_link\n");
		builder.append("\n");
		builder.append("JpipeProduce = Callable[[str, Any], None]\n");
		builder.append("\n\n");
	}

	private void exportModelBody(JustificationModel<?> model) {
		currentModelName = model.getName();
		model.conclusion().ifPresent(c -> c.accept(this));
		model.getElements().forEach(e -> e.accept(this));
	}

	private void appendMethod(JustificationElement element) {
		String qid = qualify(element.id());
		String name = LabelEscaper.toMethodName(element.label());
		String params = element instanceof Conclusion
				? ""
				: "produce: JpipeProduce";
		String decoratorArgs = jpipeDecoratorArgs(element);

		builder.append("# @jpipe_link(\"").append(qid).append("\")\n");
		builder.append("@jpipe(").append(decoratorArgs).append(")\n");
		builder.append("def ").append(name).append("(").append(params)
				.append(") -> bool:\n");
		builder.append("    \"\"\"[").append(elementTypeName(element))
				.append("] ").append(escapeDocstring(element.label()))
				.append("\"\"\"\n");
		if (element instanceof AbstractSupport) {
			builder.append("    raise NotImplementedError(\"").append(qid)
					.append(" is abstract and must be"
							+ " overridden before execution\")\n\n\n");
		} else {
			builder.append("    pass\n\n\n");
		}
	}

	private static String elementTypeName(JustificationElement element) {
		if (element instanceof Conclusion) {
			return "conclusion";
		}
		if (element instanceof SubConclusion) {
			return "sub-conclusion";
		}
		if (element instanceof Strategy) {
			return "strategy";
		}
		if (element instanceof Evidence) {
			return "evidence";
		}
		return "abstract-support";
	}

	private static String jpipeDecoratorArgs(JustificationElement element) {
		if (element instanceof Conclusion) {
			return "consume=[]";
		}
		if (element instanceof Evidence || element instanceof AbstractSupport) {
			return "produce=[]";
		}
		return "produce=[], consume=[]";
	}

	private String qualify(String elementId) {
		return currentModelName + ":" + elementId;
	}

	private static String escapeDocstring(String label) {
		return label.replace("\\", "\\\\").replace("\"", "\\\"");
	}
}
