package ca.mcscert.jpipe.visitor;

import static org.assertj.core.api.Assertions.assertThat;

import ca.mcscert.jpipe.model.Justification;
import ca.mcscert.jpipe.model.Template;
import ca.mcscert.jpipe.model.elements.AbstractSupport;
import ca.mcscert.jpipe.model.elements.Conclusion;
import ca.mcscert.jpipe.model.elements.Evidence;
import ca.mcscert.jpipe.model.elements.Strategy;
import org.junit.jupiter.api.Test;

class PythonExporterTest {

	private static Justification simpleJustification() {
		Justification j = new Justification("j");
		Conclusion c = new Conclusion("c", "The system is correct");
		Strategy s = new Strategy("s", "Testing");
		Evidence e = new Evidence("e1", "Test results");
		j.setConclusion(c);
		j.addElement(s);
		j.addElement(e);
		s.addSupport(e);
		c.addSupport(s);
		return j;
	}

	@Test
	void export_methodNamesAreSnakeCaseOfLabels() {
		String py = new PythonExporter().export(simpleJustification());

		assertThat(py).contains("def the_system_is_correct(");
		assertThat(py).contains("def testing(");
		assertThat(py).contains("def test_results(");
	}

	@Test
	void export_conclusionHasNoProduceParam() {
		String py = new PythonExporter().export(simpleJustification());

		assertThat(py).contains("def the_system_is_correct() -> bool:");
	}

	@Test
	void export_nonConclusionElementsHaveProduceParam() {
		String py = new PythonExporter().export(simpleJustification());

		assertThat(py).contains("def testing(produce: JpipeProduce) -> bool:");
		assertThat(py)
				.contains("def test_results(produce: JpipeProduce) -> bool:");
	}

	@Test
	void export_jpipeLinkIsCommented() {
		String py = new PythonExporter().export(simpleJustification());

		assertThat(py).contains("# @jpipe_link(\"j:c\")");
		assertThat(py).contains("# @jpipe_link(\"j:s\")");
		assertThat(py).contains("# @jpipe_link(\"j:e1\")");
		assertThat(py).doesNotContain("\n@jpipe_link(");
	}

	@Test
	void export_decoratorArgsReflectElementRole() {
		String py = new PythonExporter().export(simpleJustification());

		// Conclusion: top of graph — no produce
		assertThat(py).contains("# @jpipe_link(\"j:c\")\n@jpipe(consume=[])");
		// Strategy: middle — both
		assertThat(py).contains(
				"# @jpipe_link(\"j:s\")\n@jpipe(produce=[], consume=[])");
		// Evidence: leaf — no consume
		assertThat(py).contains("# @jpipe_link(\"j:e1\")\n@jpipe(produce=[])");
	}

	@Test
	void export_preambleContainsImportsAndTypeAlias() {
		String py = new PythonExporter().export(simpleJustification());

		assertThat(py).contains("from typing import Any, Callable");
		assertThat(py).contains("from jpipe_runner.framework.decorators"
				+ ".jpipe_decorator import jpipe");
		assertThat(py).contains("# from jpipe_runner.framework.decorators"
				+ ".jpipe_decorator import jpipe_link");
		assertThat(py).contains("JpipeProduce = Callable[[str, Any], None]");
	}

	@Test
	void export_withSourcePath_includesHeader() {
		String py = new PythonExporter().export(simpleJustification(),
				"examples/simple.jd");

		assertThat(py).contains("# Generated by jPipe");
		assertThat(py).contains("# Source : examples/simple.jd");
		assertThat(py).contains("# Date   :");
	}

	@Test
	void export_withoutSourcePath_noHeader() {
		String py = new PythonExporter().export(simpleJustification());

		assertThat(py).doesNotContain("# Generated by jPipe");
	}

	@Test
	void export_abstractSupportRaisesNotImplementedError() {
		Template t = new Template("t");
		Conclusion c = new Conclusion("c", "Conclusion");
		Strategy s = new Strategy("s", "Strategy");
		AbstractSupport abs = new AbstractSupport("abs", "Abstract step");
		t.setConclusion(c);
		t.addElement(s);
		t.addElement(abs);
		s.addSupport(abs);
		c.addSupport(s);

		String py = new PythonExporter().export(t);

		assertThat(py).contains("raise NotImplementedError(\"t:abs is abstract"
				+ " and must be overridden before execution\")");
		assertThat(py).doesNotContain("def abstract_step():\n    pass");
	}

	@Test
	void export_docstringIncludesTypeAndLabel() {
		String py = new PythonExporter().export(simpleJustification());

		assertThat(py)
				.contains("\"\"\"[conclusion] The system is correct\"\"\"");
		assertThat(py).contains("\"\"\"[strategy] Testing\"\"\"");
		assertThat(py).contains("\"\"\"[evidence] Test results\"\"\"");
	}

	@Test
	void export_labelWithSpecialChars_methodNameEscapedDocstringPreserved() {
		Justification j = new Justification("j");
		Conclusion c = new Conclusion("c", "Accuracy <= 0.85");
		j.setConclusion(c);

		String py = new PythonExporter().export(j);

		assertThat(py).contains("def accuracy_0_85() -> bool:");
		assertThat(py).contains("\"\"\"[conclusion] Accuracy <= 0.85\"\"\"");
	}
}
