package ca.mcscert.jpipe.visitor;

import static org.assertj.core.api.Assertions.assertThat;

import ca.mcscert.jpipe.model.Justification;
import ca.mcscert.jpipe.model.Template;
import ca.mcscert.jpipe.model.elements.AbstractSupport;
import ca.mcscert.jpipe.model.elements.Conclusion;
import ca.mcscert.jpipe.model.elements.Strategy;
import org.junit.jupiter.api.Test;

class PythonExporterTest {

	@Test
	void export_methodNamesAreSnakeCaseOfLabels() {
		String py = new PythonExporter()
				.export(ModelFixtures.simpleJustification());

		assertThat(py).contains("def the_system_is_correct(", "def testing(",
				"def test_results(");
	}

	@Test
	void export_conclusionHasNoProduceParam() {
		String py = new PythonExporter()
				.export(ModelFixtures.simpleJustification());

		assertThat(py).contains("def the_system_is_correct() -> bool:");
	}

	@Test
	void export_nonConclusionElementsHaveProduceParam() {
		String py = new PythonExporter()
				.export(ModelFixtures.simpleJustification());

		assertThat(py).contains("def testing(produce: JpipeProduce) -> bool:",
				"def test_results(produce: JpipeProduce) -> bool:");
	}

	@Test
	void export_jpipeLinkIsCommented() {
		String py = new PythonExporter()
				.export(ModelFixtures.simpleJustification());

		assertThat(py).contains("# @jpipe_link(\"j:c\")",
				"# @jpipe_link(\"j:s\")", "# @jpipe_link(\"j:e1\")");
		assertThat(py).doesNotContain("\n@jpipe_link(");
	}

	@Test
	void export_decoratorArgsReflectElementRole() {
		String py = new PythonExporter()
				.export(ModelFixtures.simpleJustification());

		assertThat(py).contains("# @jpipe_link(\"j:c\")\n@jpipe(consume=[])",
				"# @jpipe_link(\"j:s\")\n@jpipe(produce=[], consume=[])",
				"# @jpipe_link(\"j:e1\")\n@jpipe(produce=[])");
	}

	@Test
	void export_preambleContainsImportsAndTypeAlias() {
		String py = new PythonExporter()
				.export(ModelFixtures.simpleJustification());

		assertThat(py).contains("from typing import Any, Callable",
				"from jpipe_runner.framework.decorators"
						+ ".jpipe_decorator import jpipe",
				"# from jpipe_runner.framework.decorators"
						+ ".jpipe_decorator import jpipe_link",
				"JpipeProduce = Callable[[str, Any], None]");
	}

	@Test
	void export_withSourcePath_includesHeader() {
		String py = new PythonExporter().export(
				ModelFixtures.simpleJustification(), "examples/simple.jd");

		assertThat(py).contains("# Generated by jPipe",
				"# Source : examples/simple.jd", "# Date   :");
	}

	@Test
	void export_withoutSourcePath_noHeader() {
		String py = new PythonExporter()
				.export(ModelFixtures.simpleJustification());

		assertThat(py).doesNotContain("# Generated by jPipe");
	}

	@Test
	void export_abstractSupportRaisesNotImplementedError() {
		Template t = new Template("t");
		Conclusion c = new Conclusion("c", "Conclusion");
		Strategy s = new Strategy("s", "Strategy");
		AbstractSupport abs = new AbstractSupport("abs", "Abstract step");
		t.setConclusion(c);
		t.addElement(s);
		t.addElement(abs);
		s.addSupport(abs);
		c.addSupport(s);

		String py = new PythonExporter().export(t);

		assertThat(py).contains("raise NotImplementedError(\"t:abs is abstract"
				+ " and must be overridden before execution\")");
		assertThat(py).doesNotContain("def abstract_step():\n    pass");
	}

	@Test
	void export_docstringIncludesTypeAndLabel() {
		String py = new PythonExporter()
				.export(ModelFixtures.simpleJustification());

		assertThat(py).contains(
				"\"\"\"[conclusion] The system is correct\"\"\"",
				"\"\"\"[strategy] Testing\"\"\"",
				"\"\"\"[evidence] Test results\"\"\"");
	}

	@Test
	void export_labelWithSpecialChars_methodNameEscapedDocstringPreserved() {
		Justification j = new Justification("j");
		Conclusion c = new Conclusion("c", "Accuracy <= 0.85");
		j.setConclusion(c);

		String py = new PythonExporter().export(j);

		assertThat(py).contains("def accuracy_0_85() -> bool:",
				"\"\"\"[conclusion] Accuracy <= 0.85\"\"\"");
	}
}
